[build]
  command = "node scripts/fetch-gold.mjs"
  publish = "."

[functions]
  directory = "netlify/functions"

[functions."trigger-build"]
  schedule = "0 5,12,20 * * *" # ثلاث مرات يوميًا (UTC)

[functions."x-trends-refresh"]
  schedule = "*/30 * * * *" # كل 30 دقيقة (UTC) ≈ 48 مرة يوميًا
